# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks! :linkage => :static

target 'AccountKeeper' do
    # Rx
    pod 'RxViewController'
    pod 'RxSwift'
    pod 'RxCocoa'

    # Core
    pod 'Reusable', '~> 4.1'
    pod 'Then', '~> 2.7'
    pod 'SwiftGen', '~> 6.0'
    
    # Others
    pod 'MagicalRecord', '2.3.0'
    pod 'MBProgressHUD', '~> 1.2'
    
    # Database
    pod 'RealmSwift', '~>10'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end
end
